version: "3.9"
services:
  web:
    build: ./Front_end/point-news
    ports:
      - 3000:3000
  api:
    build: ./Back_end
    ports:
      - 5001:5001
    
  db: 
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - cache:/data

volumes:
  cache:
    